// bmk[*][0] : folder header
//		bmk[*][0][0] : indent level,  bmk[*][0][2] : 1=expand / 0 = collapse,  bmk[*][0][3] : 1='Open All' button,
// bmk[*][>0] = bookmark
//		bmk[*][>0][0] = (-1:blank line, 0:new line, 1:same line)
var bmk = [
	[	[0, "Daily News", 1, 1],
		[0, "http://apod.nasa.gov/apod/astropix.html", "Astronomy Picture of the Day"],
		[0, "https://twitter.com/dailygalaxy", "The Daily Galaxy Twitter"],
		[0, "http://www.zdnet.co.kr/news/news_list.asp", "지디넷코리아 - 최신 뉴스"],
		[0, "http://www.techholic.co.kr/news/articleList.html?sc_section_code=S1N1&view_type=sm", "테크홀릭 - News Archives"],
		[0, "http://www.coolenjoy.net/bbs/board.php?bo_table=38", "쿨앤조이 뉴스/신제품"],
		[0, "http://www.parkoz.com/zboard/zboard.php?id=int_news", "파코즈 - 해외 하드웨어 뉴스"],
		[1, "http://www.parkoz.com/zboard/zboard.php?id=int_vganews", "해외 그래픽"],
		[1, "http://www.parkoz.com/zboard/zboard.php?id=dm_techinfo", "해외 미디어"],
		[1, "http://www.parkoz.com/zboard/zboard.php?id=mb_techinfo", "해외 모바일"],
//		[-2],
		[0, "http://www.dpreview.com/", "Digital Photography Review"],
		[0, "http://www.slrclub.com/bbs/zboard.php?id=newproduct_sony", "SLR클럽 Sony 신제품게시판"],
		[1, "http://www.slrclub.com/bbs/zboard.php?id=newproduct_nikon", "니콘 신제품"],
		[1, "http://www.slrclub.com/bbs/zboard.php?id=newproduct", "캐논 신제품"]
	],
	[	[0, 'Portal', 1, 0],
		[0,	"http://en.wikipedia.org/wiki/Main_Page", "Wikipedia, the free encyclopedia"],
		[1, "http://ko.wikipedia.org/wiki/%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC:%EB%8C%80%EB%AC%B8", "위키백과, 우리 모두의 백과사전"],
		[0, "http://www.daum.net/", "Daum - 모으다 잇다 흔들다"],
		[1, "http://map.daum.net/", "지도 "],
		[1, "http://dic.daum.net/", "어학사전"],
		[0, "http://www.naver.com/", "네이버 :: 나의 경쟁력"],
		[1, "http://map.naver.com/", "지도 "],
		[1, "http://dic.naver.com/", "사전 "],
		[1, "http://translate.naver.com/#/ko/en", "번역 "],
		[1, "https://memo.naver.com/", "메모 "],
		[0, "https://www.google.com/", "Google"],
		[1, "https://gmail.com/", "Gmail "],
		[1, "https://www.google.co.kr/intl/ko/docs/about/", "Docs "],
		[1, "https://drive.google.com/drive/", "Drive "],
		[1, "https://translate.google.co.kr/?hl=ko&tab=wT", "번역 "],
		[1, "https://www.google.co.kr/maps/", "Maps "],
		[1, "https://play.google.com/store?hl=ko", "Play "],
		[1, "https://www.youtube.com/", "YouTube"],
		[-1],
		[0, "http://movie.naver.com/", "네이버 영화 : 영화와 처음 만나는 곳"],
		[0, "http://www.imdb.com/search/", "IMDB Advanced Search"],
		[0, "http://www.allmovie.com/", "AllMovie | Movie Search, Guide, Recommendations, and Reviews"],
		[0, "http://www.rottentomatoes.com/", "Rotten Tomatoes"],
		[0, "http://www.maniadb.com/?", "maniadb.com - all that music :: maniadb.com"],
		[0, "http://www.allmusic.com/", "AllMusic | Music Search, Recommendations, Videos and Reviews"],
		[-1],
		[0, "http://www.yonhapnews.co.kr/it/2408000001.html", "연합뉴스 - IT/과학 전체기사"],
		[0, "http://news.danawa.com/News_List_List.php", "전체 기사 :: 행복쇼핑의 시작! 다나와"]
	],
	[	[1, "SNS & BBS", 1, 0],
		[0, "https://twitter.com/login", "Twitter Login"],
		[0, "https://www.facebook.com/", "Facebook"],
		[0, "https://brunch.co.kr/", "카카오 브런치"],
		[0, "http://post.naver.com/navigator.nhn", "네이버 포스트"],
		[-1],
		[0, "https://namu.wiki/", "나무 위키"],
		[0, "http://windowsforum.kr/", "윈도우 포럼"],
		[0, "http://osmanias.com/", "OSMANIA - 오에스매니아"],
		[-1],
		[0, "http://pdh0710.dothome.co.kr/", "dothome"],
		[1, "http://pdh0710.woobi.co.kr/", "woobi"]
	],
	[	[0, "Develope", 1, 0],
		[0, "https://stackoverflow.com/", "StackOverflow"],
		[0, "https://github.com/", "GitHub"],
		[1, "https://pages.github.com/", "GitHub Pages"],
		[0, "https://www.w3schools.com/", "w3schools"],
		[0, "https://www.phpschool.com/", "PHPschool"],
		[-1],
		[0, "https://nodejs.org/", "Node.js"],
		[0, "http://php.net/", "PHP"],
		[0, "https://www.python.org/", "Python"],
		[0, "http://www.lua.org/", "Lua"],
		[0, "http://lesscss.org/", "{less}"],
 		[0, "http://www.typescriptlang.org/", "TypeScript"],
		[1, "https://code.visualstudio.com/", "VisualStudio Code"],
		[-1],
		[0, "https://www.mongodb.com/", "Mongodb.com"],
		[0, "http://www.couchbase.com/", "Couchbase"],
		[0, "https://mariadb.org/", "MariaDB"],
		[0, "https://www.mysql.com/", "MySQL"],
		[0, "https://www.postgresql.org/", "PostgreSQL"],
		[-1],
		[0, "http://nginx.org/", "Nginx"],
		[1, "https://forum.nginx.org/", "Forum"],
		[0, "https://httpd.apache.org/", "Apache HTTPd"],
		[1, "https://www.apachelounge.com/", "Apache Lounge"],
		[0, "http://www.pcre.org/", "PCRE - Perl Compatible Regular Expressions"],
		[0, "http://www.zlib.net/", "zlib"]
	],
	[	[1, "Security", 1, 0],
		[0, "https://www.openssl.org/", "OpenSSL"],
		[0, "https://www.snort.org/", "Snort"],
		[0, "https://suricata-ids.org/", "Suricata"],
		[0, "http://ossec.github.io/", "OSSEC"],
		[0, "http://netfilter.org/", "netfilter"],
		[1, "http://netfilter.org/projects/nftables/", "nftables"]
	],
	[	[1, 'Tip', 1, 0],
		[0, "http://news.softpedia.com/news/How-to-Install-and-Run-Android-Apps-in-a-Linux-OS-477407.shtml", "How to Install and Run Android Apps in a Linux OS - Softpedia"],
		[0, "http://superuser.com/questions/247651/how-does-one-install-an-extension-for-chrome-browser-from-the-local-file-system", "How does one install an extension for Chrome browser from the local file system? - Super User"]
	],
	[	[0, 'Util', 1, 0],
		[0, "http://speller.cs.pusan.ac.kr/", "한국어 맞춤법/문법 검사기"],
		[0, "http://www.wolframalpha.com/?fp=right", "Wolfram|Alpha: Computational Knowledge Engine"],
		[0, "https://www.desmos.com/calculator", "Desmos Graphing Calculator"],
		[0, "http://www.adobe.com/software/flash/about/", "Check Adobe Flash player version"],
		[0, "https://robinlinus.github.io/socialmedia-leak/", "Your Social Media Fingerprint"],
		[-1],
		[0, "c.html", "모니터 색조정"],
		[1, "colors.html", "Color Bars"],
		[1, "colors_fine.html", "Color Bars Fine"],
		[1, "colors_rotate.html", "불량화소 검사"],
		[-1],
		[0, "http://tinyurl.com/", "TinyURL.com - shorten that long URL into a tiny URL"],
		[0, "http://www.mxtoolbox.com/", "MX Lookup Tool - Check your DNS MX Records online"],
		[0, "http://whois.kisa.or.kr/kor/", "KISA - Whois Search"],
		[0, "http://ipaddress.com/", "What Is My IP Address?"],
		[0, "https://macvendors.com/", "Find MAC Address Vendors"]
	],
	[	[1, "Program", 1, 0],
		[0, "https://www.virtualbox.org/", "Oracle VM VirtualBox"],
		[0, "https://notepad-plus-plus.org/", "Notepad++ Home"],
		[0, "http://www.faststone.org/", "FastStone Image Viewer"],
		[0, "https://www.sumatrapdfreader.org/", "Sumatra Free PDF Reader"],
		[-1],
		[0, "https://www.freefilesync.org/", "FreeFileSync"],
		[0, "https://www.chiark.greenend.org.uk/~sgtatham/putty/", "PuTTY"],
		[0, "https://winscp.net/eng/index.php", "WinSCP"],
		[0, "http://www.uvnc.com/", "UltraVNC VNC Official"],
		[0, "http://www.nirsoft.net/", "NirSoft : provides small and useful freeware utilities"]
	],
	[	[1, "Torrent", 1, 0],
		[0, "http://www.bunyuc.com/", "번역 포럼"],
		[0, "http://jamak.kr/bbs/board.php?bo_table=tr_jamak", "자막 1 페이지"],
		[0, "http://bitsnoop.com/", "Bitsnoop P2P Search - 20.9 Million Valid Torrents"],
		[0, "https://rarbg.to", "RARBG Rarbg Torrents"],
		[0, "https://twitter.com/publichdto", "PublicHD Twitter"],
		[0, "https://torrentkim5.net/", "토렌트김"],
		[1, "https://twitter.com/torrentcupnet", "토런트김 트위터"],
		[0, "http://www.torrentgood.com/", "http://torrentgood.com/"],
		[0, "https://torrenthaja.com/", "토렌트하자"],
		[0, "https://torrentgirls.com/", "토렌트걸"]
	],
	[	[2, 'Daily', 1, 1],
		[0, "http://www.cineast.co.kr/bbs/board.php?bo_table=psd_caption", "씨네스트 - 자막자료실"],
		[0, "https://torrentgirl2.com/b/torrent_movie_eng", "토렌트걸 - 외국영화"],
		[0, "https://torrentkim10.net/torrent_movie/torrent1.htm", "토렌트김 - 영화 1페이지"],
		[0, "https://rarbg.to/torrents.php?search=&category%5B%5D=47&category%5B%5D=42&category%5B%5D=46", "RARBG Rarbg Torrents, Films"]
	],
	[	[0, "News0", 1, 0],
		[0, "http://apod.nasa.gov/apod/astropix.html", "Astronomy Picture of the Day"],
		[0, "https://twitter.com/dailygalaxy", "The Daily Galaxy Twitter"],
		[0, "http://www.zdnet.co.kr/news/news_list.asp", "지디넷코리아 - 최신 뉴스"],
		[0, "http://www.techholic.co.kr/news/articleList.html?sc_section_code=S1N1&view_type=sm", "테크홀릭 - News Archives"]
	],
	[	[1, "Archive1", 1, 0],
		[0, "http://www.yonhapnews.co.kr/it/2408000001.html", "연합뉴스 - IT/과학 전체기사"],
		[0, "http://news.danawa.com/News_List_List.php", "전체 기사 :: 행복쇼핑의 시작! 다나와"]
	],
	[	[2, "Archive2", 1, 0],
		[0, "http://www.yonhapnews.co.kr/it/2408000001.html", "연합뉴스 - IT/과학 전체기사"],
		[0, "http://news.danawa.com/News_List_List.php", "전체 기사 :: 행복쇼핑의 시작! 다나와"]
	],
	[	[3, "Archive3", 1, 0],
		[0, "http://www.yonhapnews.co.kr/it/2408000001.html", "연합뉴스 - IT/과학 전체기사"],
		[0, "http://news.danawa.com/News_List_List.php", "전체 기사 :: 행복쇼핑의 시작! 다나와"]
	],
	[	[4, "Archive4", 1, 0],
		[0, "http://www.yonhapnews.co.kr/it/2408000001.html", "연합뉴스 - IT/과학 전체기사"],
		[0, "http://news.danawa.com/News_List_List.php", "전체 기사 :: 행복쇼핑의 시작! 다나와"]
	],
	[	[1, "SNS & BBS", 1, 0],
		[0, "https://twitter.com/login", "Twitter Login"],
		[0, "https://www.facebook.com/", "Facebook"],
		[0, "https://brunch.co.kr/", "카카오 브런치"],
		[0, "http://post.naver.com/navigator.nhn", "네이버 포스트"],
		[-1],
		[0, "https://namu.wiki/", "나무 위키"],
		[0, "http://windowsforum.kr/", "윈도우 포럼"],
		[0, "http://osmanias.com/", "OSMANIA - 오에스매니아"],
		[-1],
		[0, "http://pdh0710.dothome.co.kr/", "dothome"],
		[1, "http://pdh0710.woobi.co.kr/", "woobi"]
	],
	[	[2, 'Tip', 1, 0],
		[0, "http://news.softpedia.com/news/How-to-Install-and-Run-Android-Apps-in-a-Linux-OS-477407.shtml", "How to Install and Run Android Apps in a Linux OS - Softpedia"],
		[0, "http://superuser.com/questions/247651/how-does-one-install-an-extension-for-chrome-browser-from-the-local-file-system", "How does one install an extension for Chrome browser from the local file system? - Super User"],
		[0, "http://news.softpedia.com/news/How-to-Install-and-Run-Android-Apps-in-a-Linux-OS-477407.shtml", "How to Install and Run Android Apps in a Linux OS - Softpedia"],
		[1, "http://superuser.com/questions/247651/how-does-one-install-an-extension-for-chrome-browser-from-the-local-file-system", "How does one install an extension for Chrome browser from the local file system? - Super User"]
	],
	[	[1, 'Shop', 1, 0],
		[0, "http://www.danawa.com/", "행복쇼핑의 시작! 다나와 (가격비교)"],
		[1, "http://dmall.danawa.com/", "장터"],
		[0, "http://www.enuri.com/", "에누리(가격비교) eNuri.com"],
		[0, "http://shopping.naver.com/", "네이버 지식쇼핑 : 대한민국 쇼핑몰 총집합!"],
		[0, "http://member.auction.co.kr/authenticate/?url=http%3a%2f%2fmember.auction.co.kr%2fMyauction%2fDefault.aspx%3ffrm%3dhometab", "옥션"],
		[1, "http://signin.gmarket.co.kr/LogIn/LogIn?URL=http://myg.gmarket.co.kr/", "G마켓"],
		[0, "https://login.11st.co.kr/login/Login.tmall?returnURL=http%3A%2F%2Fbuy.11st.co.kr%2Forder%2FmyTmall.tmall%3Fmethod%3DgetMyTmallMain", "11번가"],
		[0, "http://www.interpark.com/member/login.do?_method=initial&#38;imfsUserPath=%2Fmypage%2Fcommon%2FMyPage.do&#38;imfsUserQuery=logintgt%3Dmypage%26sid1%3Dgb%26sid2%3Dsvc&#38;FromLogin=Y&#38;str=null&#38;logintgt=mypage", "인터파크"],
		[0, "http://www.gsshop.com/customer/login/loginEnterGeneral.gs?returnurl=http://www.gsshop.com/mygsshop/myShopping.gs", "GS SHOP"],
		[0, "http://www.wemakeprice.com/", "예쁘다 위메프"],
		[0, "http://www.yes24.com/", "YES24 - 대한민국 대표 인터넷서점"],
		[0, "http://www.kyobobook.co.kr/index.laf", "인터넷 교보문고"],
		[0, "http://www.ypbooks.co.kr/kor_index.yp", "▒ 인터넷 영풍문고 - 대한민국 최초 인터넷 서점"],
		[0, "http://www.bugs.co.kr/", "음악은 역시, 벅스!"],
		[0, "http://www.ppomppu.co.kr/", "뽐뿌 "],
		[0, "http://www.wassada.com/", "와싸다닷컴"],
		[0, "http://cafe.naver.com/joonggonara", "중고나라 - 네이버카페"],
		[1, "http://cafe.daum.net/vmffotl", "다음카페"]
	],
	[	[1, 'Foreign', 1, 0],
		[0, "http://www.nextag.com/", "NexTag - Compare Prices"],
		[0, "https://www.amazon.com/", "Amazone"],
		[1, "http://camelcamelcamel.com/", "camelcamelcamel, Amazone Price Tracker"],
		[0, "http://www.ebay.com/", "Ebay"],
		[0, "https://www.paypal.com", "PayPal"],
		[0, "https://ko.aliexpress.com/", "Ko.AliExpress"],
		[1, "https://www.alibaba.com/", "Alibaba"],
		[0, "http://post.malltail.com/", "몰테일 - 해외직구"],
		[1, "http://www.taillist.com/", "테일리스트 - 몰테일 쇼핑"]
	]
];
